Pr add role conda
lnls-sirius/lnls-ansible pull request #200
Opened 2020-09-22 16:48 UTC by carneirofc

Install **conda** via yum or apt.

2020-09-23 19:59 UTC, lerwys reviewed
I've run ansible-lint with: `ansible-lint -x 106,503 roles/lnls-ans-role-conda` and no errors were reported.

2020-09-23 20:04 UTC, lerwys requested changes
Can we add this role to travis.yml? Something like this at the bottom of `jobs`:

```
    - BUILD_TYPE: default
      ROLE: lnls-ans-role-conda
```

2020-09-24 12:14 UTC, fernandohds564 approved these changes

2020-09-25 13:47 UTC, carneirofc commented
travis.yml has been updated to include the role lnls-ans-role-conda.

2020-09-25 14:11 UTC, lerwys approved these changes

2020-09-25 14:49 UTC, merged