lnls-ans-role-sirius-apps: add htop
lnls-sirius/lnls-ansible pull request #231
Opened 2020-12-03 22:41 UTC by xresende

2020-12-04 00:30 UTC, fernandohds564 approved these changes

2020-12-04 12:17 UTC, anacso17 approved these changes

2020-12-04 17:00 UTC, lerwys requested changes
Missing `htop/rsync` in `vars/Debian.yml`

2020-12-04 20:30 UTC, xresende commented
> Missing `htop/rsync` in `vars/Debian.yml`

done.

2020-12-06 23:35 UTC, lerwys approved these changes

2020-12-09 11:55 UTC, merged