Update BbB EDM GUI according to last IOC updates
lnls-sirius/lnls-ansible pull request #426
Opened 2024-02-05 21:34 UTC by anacso17

2024-02-05 23:15 UTC, fernandohds564 approved these changes

2024-02-07 12:24 UTC, ericonr requested changes

2024-02-07 12:24 UTC, ericonr commented on inventories/sirius/group_vars/all
> +sirius_bbb_version: "2023-update"
I will try and get a proper tag out soon so we can use that here!

2024-02-15 18:22 UTC, xresende approved these changes

2026-07-22 16:24 UTC, ericonr approved these changes
Proper tag has been applied :)

2026-07-23 11:49 UTC, xresende approved these changes

2026-07-23 12:00 UTC, afonsoln approved these changes

2026-07-23 19:32 UTC, merged